info:
  contact: {}
paths:
  /user/getByName:
    get:
      parameters:
      - description: 用户姓名
        in: query
        name: name
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: get User by name
      tags:
      - 用户
  /user/register:
    post:
      parameters:
      - description: 用户姓名
        in: formData
        name: name
        required: true
        type: string
      - description: 密码
        in: formData
        name: password
        type: string
      - description: 确认密码
        in: formData
        name: repassword
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: register User
      tags:
      - 用户
swagger: "2.0"
